### ISSUE TITLE
crash when upgrade to v1.0.4

### ISSUE THREAD

**Issue by amrg101** [MFlisar/MaterialPreferences#2]
opened settings screen and boom runtime crash at my face 

    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                	at android.text.StaticLayout.<init>(StaticLayout.java:455)
                                                                	at androidx.appcompat.widget.SwitchCompat.makeLayout(SwitchCompat.java:995)
                                                                	at androidx.appcompat.widget.SwitchCompat.onMeasure(SwitchCompat.java:916)
                                                                	at android.view.View.measure(View.java:25833)
                                                                	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
                                                                	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
                                                                	at android.view.View.measure(View.java:25833)
                                                                  .......

log of catched exception 

    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040107 a=-1}
                                                                	at android.content.res.TypedArray.getColor(TypedArray.java:529)
                                                                	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
                                                                	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
                                                                	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
                                                                	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
                                                                	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
                                                                	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
                                                                	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
                                                                	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
                                                                	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:101)
                                                                	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:72)
                                                                	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
                                                                	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.bool.databinding.WidgetSwitchBinding.inflate(WidgetSwitchBinding.java:42)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.bool.switches.SwitchViewHolder.createSubBinding(SwitchViewHolder.kt:23)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.bool.switches.SwitchViewHolder.createSubBinding(SwitchViewHolder.kt:12)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.recyclerview.viewholders.base.BaseViewHolderWithWidget$subBinding$2.invoke(BaseViewHolderWithWidget.kt:31)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.recyclerview.viewholders.base.BaseViewHolderWithWidget$subBinding$2.invoke(BaseViewHolderWithWidget.kt:31)
                                                                	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.recyclerview.viewholders.base.BaseViewHolderWithWidget.getSubBinding(BaseViewHolderWithWidget.kt:31)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.bool.switches.SwitchViewHolder.bindWidget(SwitchViewHolder.kt:26)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.bool.switches.SwitchViewHolder.bindWidget(SwitchViewHolder.kt:12)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.recyclerview.viewholders.base.BaseViewHolderWithWidget.rebind(BaseViewHolderWithWidget.kt:92)
                                                                	at com.michaelflisar.materialpreferences.preferencescreen.recyclerview.viewholders.base.BaseViewHolderWithWidget$bind$1$1.invokeSuspend(BaseViewHolderWithWidget.kt:70)

**Comment by amrg101** [comment]
I guess the problem was that it was trying to access some attributes (that was newly added) that is not present in the current app compact so changed my theme parent 
from 
`Theme.MaterialComponents.DayNight.NoActionBar`
to 
`Theme.Material3.DayNight.NoActionBar`
it worked and everything returned to normal.
